"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Directorio base del proyecto.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Llave para acceder al encriptamiento de datos de la base de datos.
SECRET_KEY = 'django-insecure-wmf9qe$(-6#m41r2)gu0%1jb8mwrz3*9iff$#zg6e2wjm$bj@7'

# SECURITY WARNING: don't run with debug turned on in production!
# Constante que cambia el modo de ejecución del servidor.
DEBUG = False

# Lista de direcciones desde las cuales podemos acceder a la aplicación (como el CORS)
# ALLOWED_HOSTS = ["127.0.0.1", "localhost"] # URLs especificas
ALLOWED_HOSTS = ["*"] # Todas las URLs, no es recomendado por seguridad.


# Application definition
# Aplicaciones instaladas y conectadas a la base de datos.
INSTALLED_APPS = [
    'django.contrib.admin', # Interfaz gráfica que podemos utilizar para manipular las entidades de la db
    'django.contrib.auth', # Implementación de DJANGO que maneja las cuentas de usuario.
    'django.contrib.contenttypes', # Restringir el tipo de contenidos que enviamos en cada petición.
    'django.contrib.sessions', # Manejar inicios de sesiones.
    'django.contrib.messages', # Manejar mensajes especiales de error o feedback al usuario.
    'django.contrib.staticfiles', # Manejador de archivos estaticos.
    'tasks', # Instalamos aplicación personalizada llamada tasks.
]

# Middlewares de validación al ejecutar peticiones.
# Se ejecuta una vez que llega una solicitud, pero antes de que el servidor procese dicha solicitud.
# Por ejemplo: Validar que un usuario inicio sesión antes de dejarlo ver un apartado.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Dirección donde se encuentran las URL's del proyecto (archivo urls.py)
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Constante de conexión de la base de datos, en este caso es una SQlite 3
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
